version: "3.3"

services:
  s3server:
    image: "bitnami/minio:latest"
    ports:
      - "9001:9001"
      - "9000:9000"
    environment:
      MINIO_SCHEME: http
      MINIO_FORCE_NEW_KEYS: "yes"
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DEFAULT_BUCKETS: 'vod-bucket:public'
      MINIO_ACCESS_KEY: foobar
      MINIO_SECRET_KEY: barfoobarfoo
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
